Added more options to PiP

diff --git a/mint/PiP b/mint/PiP
--- a/mint/PiP
+++ b/mint/PiP
@@ -1,45 +1,146 @@
 #!/usr/bin/env bash
 
-# Quick clanker-written script
+set -euo pipefail
 
-# Get screen dimensions (primary display)
+# Get primary screen dimensions
 read SW SH <<<"$(xdpyinfo | awk '/dimensions:/ {split($2,a,"x"); print a[1], a[2]}')"
 
-# Calculate quarter size (top-right)
-W=$((SW / 2))
-H=$((SH / 2))
-X=$((SW / 2))
-Y=0
+usage() {
+	cat <<EOF
+Usage:
+    PiP [SIZE] [CORNER]
 
-# Get window list
+SIZE:
+    1/1   1
+    1/2   2
+    1/4   3
+
+CORNER:
+    tl    1
+    tr    2
+    bl    3
+    br    4
+
+Examples:
+    PiP
+    PiP "1/2" br
+    PiP 2 4
+EOF
+	exit 1
+}
+
+############################
+# Size
+############################
+
+if [[ $# -ge 1 ]]; then
+	SIZE="$1"
+else
+	echo "Choose size:"
+	echo "  1) 1/1"
+	echo "  2) 1/2"
+	echo "  3) 1/4"
+	read -rp "> " SIZE
+
+	case "$SIZE" in
+	1) SIZE="1/1" ;;
+	2) SIZE="1/2" ;;
+	3) SIZE="1/4" ;;
+	esac
+fi
+
+case "$SIZE" in
+1 | 1/1)
+	W=$SW
+	H=$SH
+	;;
+2 | 1/2)
+	W=$((SW / 2))
+	H=$((SH / 2))
+	;;
+3 | 1/4)
+	W=$((SW / 4))
+	H=$((SH / 4))
+	;;
+*)
+	echo "Invalid size."
+	usage
+	;;
+esac
+
+############################
+# Corner
+############################
+
+if [[ $# -ge 2 ]]; then
+	CORNER="${2,,}"
+else
+	echo
+	echo "Choose corner:"
+	echo "  1) Top-left"
+	echo "  2) Top-right"
+	echo "  3) Bottom-left"
+	echo "  4) Bottom-right"
+	read -rp "> " CORNER
+	CORNER="${CORNER,,}"
+fi
+
+case "$CORNER" in
+1 | tl)
+	X=0
+	Y=0
+	;;
+2 | tr)
+	X=$((SW - W))
+	Y=0
+	;;
+3 | bl)
+	X=0
+	Y=$((SH - H))
+	;;
+4 | br)
+	X=$((SW - W))
+	Y=$((SH - H))
+	;;
+*)
+	echo "Invalid corner."
+	usage
+	;;
+esac
+
+############################
+# Find PiP window
+############################
+
 mapfile -t WINDOWS < <(wmctrl -l)
 
-# Try to find Picture-in-Picture automatically
-for i in "${!WINDOWS[@]}"; do
-	if [[ "${WINDOWS[$i]}" == *"Picture-in-Picture"* ]]; then
-		WIN_ID=$(echo "${WINDOWS[$i]}" | awk '{print $1}')
+for WINDOW in "${WINDOWS[@]}"; do
+	if [[ "$WINDOW" == *"Picture-in-Picture"* ]]; then
+		WIN_ID=$(awk '{print $1}' <<<"$WINDOW")
 		echo "Auto-selected PiP window: $WIN_ID"
 		wmctrl -i -r "$WIN_ID" -e "0,$X,$Y,$W,$H"
 		exit 0
 	fi
 done
 
-# Otherwise, show numbered list
+############################
+# Manual selection
+############################
+
+echo
 echo "Select a window:"
+
 for i in "${!WINDOWS[@]}"; do
-	printf "%d) %s\n" "$((i + 1))" "${WINDOWS[$i]}"
+	printf "%2d) %s\n" "$((i + 1))" "${WINDOWS[$i]}"
 done
 
-read -rp "Enter number: " CHOICE
+read -rp "> " CHOICE
 
-# Validate input like a responsible adult
 if ! [[ "$CHOICE" =~ ^[0-9]+$ ]] || ((CHOICE < 1 || CHOICE > ${#WINDOWS[@]})); then
-	echo "Invalid selection. Congratulations."
+	echo "Invalid selection. Humanity had one job."
 	exit 1
 fi
 
-# Extract chosen window ID
-WIN_ID=$(echo "${WINDOWS[$((CHOICE - 1))]}" | awk '{print $1}')
+WIN_ID=$(awk '{print $1}' <<<"${WINDOWS[$((CHOICE - 1))]}")
 
-# Resize it
 wmctrl -i -r "$WIN_ID" -e "0,$X,$Y,$W,$H"
