prettier and shfmt

diff --git a/utils/better-cd b/utils/better-cd
--- a/utils/better-cd
+++ b/utils/better-cd
@@ -5,12 +5,15 @@ TARGET_DIR="$1"
 
 # Check if argument is provided
 if [ -z "$TARGET_DIR" ]; then
-    echo "Usage: $0 <directory>"
-    exit 1
+	echo "Usage: $0 <directory>"
+	exit 1
 fi
 
 # Create the directory if it doesn't exist
 mkdir -p "$TARGET_DIR"
 
 # Change to the directory
-cd "$TARGET_DIR" || { echo "Failed to enter directory $TARGET_DIR"; exit 1; }
+cd "$TARGET_DIR" || {
+	echo "Failed to enter directory $TARGET_DIR"
+	exit 1
+}
diff --git a/utils/better-mv b/utils/better-mv
--- a/utils/better-mv
+++ b/utils/better-mv
@@ -4,16 +4,16 @@ set -euo pipefail
 
 # If no source or dest or too many source and dest
 if [ "$#" -ne 2 ]; then
-  echo "Usage: bmv SOURCE DEST"
-  exit 1
+	echo "Usage: bmv SOURCE DEST"
+	exit 1
 fi
 
 src="$1"
 dst="$2"
 
 if [ ! -e "$src" ]; then
-  echo "mvx: cannot stat '$src': No such file or directory"
-  exit 1
+	echo "mvx: cannot stat '$src': No such file or directory"
+	exit 1
 fi
 
 # Create temp file/dir in same filesystem as destination (safer for mv)
